
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.cesar31.threewaycode.parser;

/** CUP generated class containing symbol constants. */
public class ThreeParserSym {
  /* terminals */
  public static final int MINUS = 5;
  public static final int DIVIDE = 7;
  public static final int INTEGER = 3;
  public static final int ERROR = 12;
  public static final int SEMI = 10;
  public static final int EQUAL = 11;
  public static final int EOF = 0;
  public static final int PLUS = 4;
  public static final int ID = 2;
  public static final int error = 1;
  public static final int RPAREN = 9;
  public static final int TIMES = 6;
  public static final int LPAREN = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "INTEGER",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "LPAREN",
  "RPAREN",
  "SEMI",
  "EQUAL",
  "ERROR"
  };
}

